name: Pull Request on Master

on:
  pull_request:
    branches: [master]

jobs:
  #call-workflow-build-and-test:
  #  name: Build and Test
  #  uses: ./.github/workflows/workflow-build-test.yaml
  comment:
    - name: Create a comment
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })