name: Pull Request on Master

on:
  pull_request:
    branches: [master]

jobs:
  call-workflow-build-and-test:
    name: Build and Test
    uses: ./.github/workflows/workflow-build-test.yaml

  call-workflow-preview-deploy:
    name: Pre Deploy
    uses: ./.github/workflows/workflow-preview-deploy.yaml
    secrets: inherit
    needs: call-workflow-build-and-test

  comment-workflow:
    runs-on: ubuntu-latest
    needs: call-workflow-preview-deploy
    permissions:
      pull-requests: write

    steps:
      - name: Create a comment
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ needs.call-workflow-preview-deploy.outputs.preview-deploy-result }}"
            })